name: Check build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 17.x, 18.x]
    env:
      DEPLOYMENT_NODE_VERSION: '18.x'
    steps:
      - name: Check out sources
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install build dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Lint with ESLint
        run: npx eslint src/

      - name: Deploy with gh-pages
        if:
          github.ref_name == 'main' &&
          matrix.node-version == env.DEPLOYMENT_NODE_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages --no-history --dist build --user "github-actions-bot <support+actions@github.com>"
